```{r results}

# This file contains the results: 
# ...


```


# Prereg paragraph 

More precisely, this work has two overarching aims: 

First, to systematically assess reporting practices in human fear conditioning research regarding the use of data transformation procedures and examination of statistical assumptions, such as the normal distribution of residuals, and the handling of outliers during fear acquisition training throughout a systematic review of the literature. This aim is directly linked to the application of data transformation procedures, critical in ensuring these assumptions are met and outliers are effectively managed.

Second, to systematically extract data transformation procedures used in the field of human fear conditioning from the literature. These will serve as a basis for a subsequent study (separate Preregistration), in which we will comprehensively examine in a multiverse analysis how the identified data transformation procedures affect the distribution of the data and ultimately reliability and effect sizes.


# Analysis ideas

## To prepare in advance:

- add columns to the dataset: would have testing of assumptions been necessary?


## Aim 1: Analysis

Calculate reporting frequencies of
- precise statement if it was applied on a trial-level, averaged first asf.
- a rationale behind the data transformation
- assumption testing
- outlier and criterion
- open science practices?
- specific statistical models?

Maybe identify patterns across studies
- Do studies that report one data transformation aspect also report the others? -> e.g., if trial-level, then also rationale
-> possible plot: spider

## Möglicher Aufbau
### a. Descriptives (Replication? in Supplementary)
n_with_exclusions, n_female_total, age_mean_total, age_sd_total, mental health disorder exclusion, Was an individual level analysis conducted

### b. Assumption Checking (am Beispiel hier mit Normality)
- Welches Statistische Verfahren vorgeschalten? 
- Mario konsultieren
eine Frage -> dann Sanky mit Antwort und Anzahl, Tina/Mana bars, doughnuts, lolli, waffle/heatmap e.g., Was the normal distribution checked?, If yes, how?, before/after, etc.
FRAGEN
- Was the normal distribution checked?
- Was the homoscedasticity checked?
- Was the sphericity checked?
- Was the independence of residuals checked?
- Was the linearity checked?
- Was the multicollinearity checked?

### c. Transformation Practices
specification of data transformation method, rationale, was the transformation applied on trial or average level
the different data transformations (how many studies use raw data?)

### d. Outlier Practices
outlier removal reported?, outlier criterion, outlier refer to
z.B. Barplots of how often outlier removal is reported
Compare frequencies of different criteria (e.g., +/-2SD vs. +/-3SD)

### e. Outcome Measures
Binary presence/absence analysis
pattern identifizieren
the use of different psychophysioligical outcomes?scr, emg 
dot-plot-simulation

### f. Statistical Models
Statistical model, Main statistical test, further specification
- Count and visualize test types (t-test, ANOVA, mixed models)
- Compare test choice across study types or transformation practices
- Association with whether assumptions were tested


## Aim 2: Prepare a list including all identified transformations per outcome measure

## Possible plots
### For frequencies:
- Doughnut
- Pie
- Waffle
- Lollipop
- heatmaps