---
title: "Task_Force_SpecCurve"
author: "Alina Koppold"
date: "2023-11-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(haven)
library(scales)
library(BayesFactor)
library(MASS)
library(patchwork)
```

``` {r load-prepare-data}

# Enter name of the dataset that should be loaded here
data_multiverse = read_rds("data/Reutter_Pupil.rds")

# Factorize transformation and range correction type
data_multiverse$range_cor <- as.factor(data_multiverse$range_cor)
data_multiverse$range_cor <- factor(data_multiverse$range_cor, levels = c("none","cs","us"))
data_multiverse$transformation <- as.factor(data_multiverse$transformation)
data_multiverse$transformation <- factor(data_multiverse$transformation, levels = c("raw", "box", "log", "sqr", "ztr"))

```


# Visualization
### Specification curve for regular pairwise t-test

```{r plot-settings}

# set colors for plotting
# set colors
clrs <- c("#D1D646",
"#F97068",
"#57C4E5",
"#17A398",
"#A05C7B",
"#435058")
barplot(1:6, col=clrs)
# set sizes 
size_point <- 5  # lines in categories under spec curve
size_text  <- 12 # text and ticks on x and y axis

fig_w <- 10
fig_h <- 7
fig_res <- 300

```

```{r plot-curves-effect-size}

# WITHOUT BOXCOX TRANSFORMATION TO DIFFERENTIATE OTHER TRANSFORMATIONS BETTER
data_multiverse = data_multiverse %>% filter(transformation != "box")

# Data must be ordered separately for effect size and rel -> set up a new data set
data_multi_es <- data_multiverse

# Add index to order by effect size
# We have n + 1 unique approaches
data_multi_es$approach_num <-  1:nrow(data_multi_es)
data_multi_es[order(data_multi_es$effect),'approach_eff_order'] <-  1:nrow(data_multi_es)

# Count number of approaches for x-axis
numb_appr_es <- nrow(data_multi_es)


# Labels
x_lab <- 'Approach number ordered by effect size'
y_lab <- 'Effect size (Hedge\'s g)'

# Order by effect size
# Colored by approach
p_effect <- data_multi_es %>%
  ggplot(aes(x = approach_eff_order, y = effect, color = transformation)) +
  geom_point() +
  geom_errorbar(aes(ymin = effect_CI95.lo, ymax = effect_CI95.hi)) +
  scale_color_manual(name = 'Transformation', values = clrs[c(1:5)],
                     labels = c("none", #"box-cox", 
                                "log-transformed", "square-root", "z-transformed")) +
  scale_x_continuous(breaks = c(1:numb_appr_es), labels = c(1:numb_appr_es)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# Plot specifications of parameters
s_effect <- ggplot(data_multi_es, aes(x = approach_eff_order, y = range_cor)) +
  geom_point(shape = '|', size = size_point) +
  scale_y_discrete(name = 'Range correction', labels = c("none", "CS corrected", "US corrected")) +
  scale_x_continuous(breaks = c(1:15), labels = c(1:15)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# Combine plots

plot_spec_effect <- p_effect / s_effect
plot_spec_effect

```



```{r plot-curves-reliability}

# Data must be ordered separately for effect size and rel -> set up a new data set
data_multi_rel <- data_multiverse

# Add index to order by size of reliability
# We have n + 1 unique approaches
data_multi_rel$approach_num <-  1:nrow(data_multi_rel)
data_multi_rel[order(data_multi_rel$rel),'approach_rel_order'] <-  1:nrow(data_multi_rel)

# Count number of approaches for x-axis
numb_appr_rel <- nrow(data_multi_rel)

# labels
x_lab <- 'Approach number ordered by size of reliability'
y_lab <- 'Reliability (split-half)'

# Order by size of reliability
# Colored by approach
p_reliability <- data_multi_rel %>%
  ggplot(aes(x = approach_rel_order, y = rel, color = transformation)) +
  geom_point() +
  geom_errorbar(aes(ymin = rel_CI95.lo, ymax = rel_CI95.hi)) +
  scale_color_manual(name = 'Transformation', values = clrs[c(1:5)], labels = c("none", "box-cox", "log-transformed", 
  "square-root", "z-transformed")) +
  scale_x_continuous(breaks = c(1:numb_appr_rel), labels = c(1:numb_appr_rel)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# plot specifications of parameters
s_reliability <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = range_cor)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Range correction', labels = c("none", "CS corrected", "US corrected")) +
    scale_x_continuous(breaks = c(1:15), labels = c(1:15)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# Combine plots

plot_spec_reliability <- p_reliability / s_reliability
plot_spec_reliability

```



```{r plot-curves-effect-size-lines-only}

# labels
x_lab <- 'Approach number ordered by effect size'
y_lab <- 'Effect size (Hedge\'s g)'

# order by effect size

p_effect <- data_multi_es %>%
  ggplot(aes(x = approach_eff_order, y = effect)) +
  geom_point() +
  geom_errorbar(aes(ymin = effect_CI95.lo, ymax = effect_CI95.hi)) +

  scale_x_continuous(breaks = c(1:numb_appr_es), labels = c(1:numb_appr_es)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# plot specifications of parameters: transformation type
s_effect_1 <- ggplot(data_multi_es, aes(x = approach_eff_order, y = transformation)) +
  geom_point(shape = '|', size = size_point) +
  scale_x_continuous(breaks = c(1:numb_appr_es), labels = c(1:numb_appr_es)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 


# plot specifications of parameters: range correction type
s_effect_2 <- ggplot(data_multi_es, aes(x = approach_eff_order, y = range_cor)) +
  geom_point(shape = '|', size = size_point) +
  scale_y_discrete(name = 'Range correction', labels = c("none", "CS corrected", "US corrected")) +
  scale_x_continuous(breaks = c(1:numb_appr_es), labels = c(1:numb_appr_es)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# Combine plots

plot_spec_effect_lines_only <- p_effect / s_effect_1 / s_effect_2
plot_spec_effect_lines_only

```
