---
title: "Task_Force_SpecCurve_Between"
author: "Alina Koppold"
date: "2023-11-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(haven)
library(scales)
library(BayesFactor)
library(MASS)
library(patchwork)
```


### Preparation Dataset 1 
```{r load-data-merz}
# loading the original data 
#X7163CM_8163CM_EDA_ac <- read_sav("data/7163CM_8163CM_EDA_ac.sav")
  
# in long format 
#load("./data/long_EDA_merz.Rdata")

# Rename some variables
#names(data_long)[grep("Versuchspersonennummer", names(data_long))] <- "id"
#names(data_long)[grep("scr", names(data_long))] <- "scr_raw"

# load new data (Marios)
data_merz = read_rds("data/Merz_multiverse.rds")

# Factorize transformation and range correction type
data_merz$range_cor <- as.factor(data_merz$range_cor)
data_merz$range_cor <- factor(data_merz$range_cor, levels = c("none","cs","us"))
data_merz$transformation <- as.factor(data_merz$transformation)
data_merz$transformation <- factor(data_merz$transformation, levels = c("raw", "box", "log", "sqr", "ztr"))


# Add variables of interest
data_merz$reinforcement_rate = "62.5"
data_merz$n = "97"
data_merz$CS_duration = "6s" 
data_merz$CS_stimuli = "picture"
data_merz$training = "instructed"
data_merz$max_us_raw = "1.96"
data_merz$max_cs_raw = "1.96"
data_merz$dataset = "Merz"

```


### Preparation Dataset 2 B07
# implementation of hedges g missing here 
# define variables of interest 
```{r load-data-B07}

data_B07 = read_rds("data/B07_multiverse.rds")

# Factorize transformation and range correction type
data_B07$range_cor <- as.factor(data_B07$range_cor)
data_B07$range_cor <- factor(data_B07$range_cor, levels = c("none","cs","us"))
data_B07$transformation <- as.factor(data_B07$transformation)
data_B07$transformation <- factor(data_B07$transformation, levels = c("raw", "box", "log", "sqr", "ztr"))


# Add variables of interest
data_B07$reinforcement_rate = "100"
data_B07$n = "113"
data_B07$CS_duration = "6s" 
data_B07$CS_stimuli = "picture"
data_B07$training = "uninstructed"
data_B07$max_us_raw = "1.49" 
data_B07$max_cs_raw = "0.89"
data_B07$dataset = "B07"


```


```{r}
merged_datasets = rbind(data_merz, data_B07)
```

# Plot needs to be adjusted

```{r plot-curves-NHST}

# set colors for plotting
# set colors
clrs <- c("#D1D646",
          "orange",
"#F97068",
"#57C4E5",
"blue",
"#17A398",
"#A05C7B",
"#435058")
barplot(1:8, col=clrs)
# set sizes 
size_point <- 5  # lines in categories under spec curve
size_text  <- 12 # text and ticks on x and y axis

fig_w <- 10
fig_h <- 7
fig_res <- 300

# labels
x_lab <- 'Approach number ordered by effect size'
y_lab <- 'Effect size (...)'

```


```{r plot-curves-effect-size}

# Data must be ordered separately for effect size and rel -> set up a new data set
data_multi_es <- merged_datasets

# Add index to order by effect size
# We have n + 1 unique approaches
data_multi_es$approach_num <-  1:nrow(data_multi_es)
data_multi_es[order(data_multi_es$effect),'approach_eff_order'] <-  1:nrow(data_multi_es)

# labels
x_lab <- 'Approach number ordered by effect size'
y_lab <- 'Effect size (Hedge\'s g)'

# order by effect size
# colored by approach
p_effect <- data_multi_es %>%
  ggplot(aes(x = approach_eff_order, y = effect, color = transformation)) +
  geom_point() +
  geom_errorbar(aes(ymin = effect_CI95.lo, ymax = effect_CI95.hi)) +
  scale_color_manual(name = 'Transformation', values = clrs[c(1:5)], labels = c("none", "box-cox", "log-transformed", 
  "square-root", "z-transformed")) +
  scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# plot specifications of parameters: range correction
s_effect_range_cor <- ggplot(data_multi_es, aes(x = approach_eff_order, y = range_cor)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Range correction', labels = c("none", "CS corrected", "US corrected")) +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: reinforcement rate
s_effect_reinf_rate <- ggplot(data_multi_es, aes(x = approach_eff_order, y = reinforcement_rate)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Reinforcement rate') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: instruction of ACQ
s_effect_instr <- ggplot(data_multi_es, aes(x = approach_eff_order, y = training)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'ACQ instruction') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: n
s_effect_n <- ggplot(data_multi_es, aes(x = approach_eff_order, y = n)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Sample size') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: max CS raw
s_effect_max_cs_raw <- ggplot(data_multi_es, aes(x = approach_eff_order, y = max_cs_raw)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Max. raw SCR to CS') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: max US raw
s_effect_max_us_raw <- ggplot(data_multi_es, aes(x = approach_eff_order, y = max_us_raw)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Max. raw SCR to US') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# Combine plots

plot_spec_effect <- p_effect / s_effect_range_cor / s_effect_reinf_rate / s_effect_instr / s_effect_n / s_effect_max_cs_raw / s_effect_max_us_raw
plot_spec_effect

```



```{r plot-curves-reliability}

# Data must be ordered separately for effect size and rel -> set up a new data set
data_multi_rel <- merged_datasets

# Add index to order by size of reliability
# We have n + 1 unique approaches
data_multi_rel$approach_num <-  1:nrow(data_multi_rel)
data_multi_rel[order(data_multi_rel$rel),'approach_rel_order'] <-  1:nrow(data_multi_rel)

# labels
x_lab <- 'Approach number ordered by size of reliability'
y_lab <- 'Reliability (split-half)'

# Order by size of reliability
# Colored by approach
p_reliability <- data_multi_rel %>%
  ggplot(aes(x = approach_rel_order, y = rel, color = transformation)) +
  geom_point() +
  geom_errorbar(aes(ymin = rel_CI95.lo, ymax = rel_CI95.hi)) +
  scale_color_manual(name = 'Transformation', values = clrs[c(1:5)], labels = c("none", "box-cox", "log-transformed", 
  "square-root", "z-transformed")) +
  scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# plot specifications of parameters: range correction
s_reliability_range_cor <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = range_cor)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Range correction', labels = c("none", "CS corrected", "US corrected")) +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: reinforcement rate
s_reliability_reinf_rate <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = reinforcement_rate)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Reinforcement rate') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: instruction of ACQ
s_reliability_instr <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = training)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'ACQ instruction') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: n
s_reliability_n <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = n)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Sample size') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: max CS raw
s_reliability_max_cs_raw <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = max_cs_raw)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Max. raw SCR to CS') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 

# plot specifications of parameters: max US raw
s_reliability_max_us_raw <- ggplot(data_multi_rel, aes(x = approach_rel_order, y = max_us_raw)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Max. raw SCR to US') +
    scale_x_continuous(breaks = c(1:30), labels = c(1:30)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 


# Combine plots

plot_spec_reliability <- p_reliability / s_reliability_range_cor / s_reliability_reinf_rate / s_reliability_instr / s_reliability_n / s_reliability_max_cs_raw / s_reliability_max_us_raw
plot_spec_reliability

```





```{r alinas-code}

########################################################################################## ALINAS CODE
# order by effect size
# colored by approach
p1 <- merged_datasets %>%
  ggplot(aes(x = approach_eff_order, y = effsize, color = dataset)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
#  scale_color_manual(name = 'Transformation', values = clrs[c(1:5)], labels = c("box cox", "log-transformed", "none", "square-root", "z-transformed")) +
 # scale_x_continuous(breaks = c(1:15), labels = c(1:15)) +
  theme_classic() +
  theme(text = element_text(size=size_text),
        legend.position = 'top') +
  xlab(x_lab) +
  ylab(y_lab) + 
  guides(color = guide_legend(nrow = 1))


# plot specifications of parameters
s1 <- ggplot(merged_datasets, aes(x = approach_eff_order, y = transf_type)) +
  geom_point(shape = '|', size = size_point) +
   #scale_color_manual(values = rep('black', length(levels(res_ttest_d$approach)) )) +
  scale_y_discrete(name = 'Dataset') +
    #scale_x_continuous(breaks = c(1:15), labels = c(1:15)) +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        legend.position = 'none') +
  theme(text = element_text(size=size_text)) 
s1

# Combine plots

plot_spec_NHST <- p1 / s1
plot_spec_NHST

```
